### ISSUE TITLE
Rectangular Jacobian matrices support

### ISSUE THREAD

**Issue by tversteeg** [rust-cv/levenberg-marquardt#10]
Thanks for the highly underrated library, it's very nice to use.

It would be nice to be able to return a non-square Jacobian matrix from the `LeastSquaresProblem::jacobian()` function. Whenever I try it I get a `termination: WrongDimension("jacobian")` as part of the report.

At least a mention of this limitation in the documentation would be nice.

Also, for my understanding: is this a mathematical limitation, a missing implementation, or am I doing something wrong?

**Comment by vadixidav** [comment]
Thank you for reporting your issue. You should be able to use `LeastSquaresProblem` with non-square matrices, which is something we use it for in Rust CV, so if it is having an issue with non-square matrices right now then I will definitely look at that.

Before I do that, I would like you to double check something. Notably, you need to make sure that your [`residuals`](https://docs.rs/levenberg-marquardt/0.10.0/levenberg_marquardt/trait.LeastSquaresProblem.html#tymethod.residuals) have M rows, your [`params`](https://docs.rs/levenberg-marquardt/0.10.0/levenberg_marquardt/trait.LeastSquaresProblem.html#tymethod.params) have N rows, and your Jacobian is MxN (rows x colums). Our example in the documentation likely isn't clear on this since it uses a square matrix, so it could be more clear by using a non-square matrix in the documentation.

If you check the above and that all seems correct, let me know, and I can investigate further. If you have a code sample that fails, I would appreciate that as well, but simply verifying for me that those things are true should be helpful. Thanks!

**Comment by tversteeg** [comment]
Thanks a lot, the problem was that the residuals I returned was the same size as the parameters. So I had 2 residuals, 2 parameters but a 2x1 Jacobian.

Maybe a message in the form of `expected $x residuals but got $y` would be better instead of the simple `jacobian` string that's returned currently?

**Comment by vadixidav** [comment]
Opened #11 to improve this error message.
